version: '3.3'

services:
  db_backup:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./${DIR}:/app/${DIR}:rw
      - ./data:/app/data:rw

  db:
    image: postgres:15-alpine3.17
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /data/postgres
    restart: unless-stopped
    ports:
      - 127.0.0.1:${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./data/postgres:/data/postgres
    command: -p ${DATABASE_PORT}
