version: '3.3'

networks:
  database:
    external: true

services:
  app:
    networks:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./${DIR}:/app/${DIR}:rw
