version: '3.3'
## Create network if your database is running outside
networks:
   database:
     external: true

services:
  app:
    networks:
       - database
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./${DIR}:/app/${DIR}:rw
