version: '3.3'

// Uncomment in case your database is running outside (in other network)
# networks:
#   database:
#     external: true

services:
  app:
    // Uncomment in case your database is running outside (in other network)
    # networks:
    #   - database
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./${DIR}:/app/${DIR}:rw
